"""Property 16: Recommendation Evidence Payload Completeness

For any recommendation generated by the engine, all required fields should be
present and non-empty: recommendationId, runId, type, affectedGoldenSet,
impactedIntentId, reason, identifiedGap, proposedAction, priority, status,
actionability.

**Validates: Requirements 8.3**
"""

from __future__ import annotations

# Feature: python-analysis-backend, Property 16: Recommendation Evidence Payload Completeness

from hypothesis import given, settings
from hypothesis import strategies as st

from engine.recommendation_engine import (
    RecommendationEngineConfig,
    generate_recommendations,
)

# ─── Strategies ──────────────────────────────────────────────────────────────

_intent_names = st.sampled_from([
    "product-search", "price-filter", "color-filter", "size-filter",
])

_classification = st.sampled_from([
    "matched", "real-only", "underrepresented", "overrepresented",
    "candidate-obsolete", "protected-retained", "golden-only",
])

_actionability = st.sampled_from([
    "action-ready", "monitor", "insufficient-evidence", "protected-override",
])

_paraphrase_classification = st.sampled_from(["narrow", "missing"])


def _coverage_metric():
    return st.fixed_dictionaries({
        "intentId": _intent_names,
        "intentLabel": _intent_names,
        "intentFamily": st.just(""),
        "classification": _classification,
        "realInputCount": st.integers(min_value=0, max_value=500),
        "realInputSharePercent": st.floats(min_value=0, max_value=100, allow_nan=False),
        "goldenSetCaseCount": st.integers(min_value=0, max_value=500),
        "goldenSetSharePercent": st.floats(min_value=0, max_value=100, allow_nan=False),
        "representationDelta": st.floats(min_value=-50, max_value=50, allow_nan=False),
        "isProtected": st.booleans(),
        "protectedClasses": st.just([]),
        "actionability": _actionability,
    })


def _paraphrase_metric():
    return st.fixed_dictionaries({
        "intentId": _intent_names,
        "paraphraseGroupId": st.text(min_size=1, max_size=10),
        "classification": _paraphrase_classification,
        "goldenParaphraseCount": st.integers(min_value=1, max_value=20),
        "realWordingVariantCount": st.integers(min_value=0, max_value=20),
        "uncoveredVariants": st.lists(st.text(min_size=1, max_size=20), max_size=5),
        "isProtected": st.booleans(),
        "hasInstabilitySignal": st.just(False),
        "outcomeVariability": st.just([]),
    })


_config = RecommendationEngineConfig(
    run_id="test-run",
    materiality_threshold=0.05,
    protected_case_rules=[],
    observation_window=30,
)

REQUIRED_FIELDS = [
    "recommendationId",
    "runId",
    "type",
    "affectedGoldenSet",
    "impactedIntentId",
    "reason",
    "identifiedGap",
    "proposedAction",
    "priority",
    "status",
    "actionability",
]


# ─── Property Tests ─────────────────────────────────────────────────────────


@given(
    coverage=st.lists(_coverage_metric(), min_size=1, max_size=5),
)
@settings(max_examples=100)
def test_coverage_recommendations_have_all_required_fields(coverage):
    """Every recommendation from coverage metrics has all required fields present and non-empty."""
    recs = generate_recommendations(coverage, [], [], _config)

    for rec in recs:
        for field in REQUIRED_FIELDS:
            assert field in rec, f"Missing field: {field}"
            assert rec[field] is not None, f"Field {field} is None"
            assert rec[field] != "", f"Field {field} is empty"


@given(
    paraphrase=st.lists(_paraphrase_metric(), min_size=1, max_size=5),
)
@settings(max_examples=100)
def test_paraphrase_recommendations_have_all_required_fields(paraphrase):
    """Every recommendation from paraphrase metrics has all required fields present and non-empty."""
    recs = generate_recommendations([], [], paraphrase, _config)

    for rec in recs:
        for field in REQUIRED_FIELDS:
            assert field in rec, f"Missing field: {field}"
            assert rec[field] is not None, f"Field {field} is None"
            assert rec[field] != "", f"Field {field} is empty"


@given(
    coverage=st.lists(_coverage_metric(), min_size=1, max_size=3),
    paraphrase=st.lists(_paraphrase_metric(), min_size=0, max_size=3),
)
@settings(max_examples=100)
def test_all_recommendations_have_valid_types(coverage, paraphrase):
    """Every recommendation has a valid recommendation type."""
    valid_types = {
        "add-new-intent", "add-examples-for-intent", "add-paraphrase-variants",
        "create-paraphrase-group", "add-unsupported-coverage",
        "add-policy-pii-coverage", "reduce-retire-obsolete", "no-update",
    }

    recs = generate_recommendations(coverage, [], paraphrase, _config)

    for rec in recs:
        assert rec["type"] in valid_types, f"Invalid type: {rec['type']}"


@given(
    coverage=st.lists(_coverage_metric(), min_size=1, max_size=3),
)
@settings(max_examples=100)
def test_all_recommendations_have_valid_priority(coverage):
    """Every recommendation has a valid priority level."""
    valid_priorities = {"critical", "high", "medium", "low"}

    recs = generate_recommendations(coverage, [], [], _config)

    for rec in recs:
        assert rec["priority"] in valid_priorities, f"Invalid priority: {rec['priority']}"
